server:
  port: 8081                  # Port
  servlet:
    context-path: /address   # Context path for API

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mobilehub_address
    username: root
    password: root1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

