server:
  port: 8080                  # Port
  servlet:
    context-path: /identity   # Context path for API

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mobilehub_identity
    username: root
    password: root1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
jwt:
  signerKey: "koNAzoN/cNgpNBC6N7JFzl8Gkycz3ryA39mWjs4q1N7YPw+dB68UcwPQPNhfY3iiIE9aTl9kC5mX0640CmPGFw" # Khóa ký JWT
  issuer: "mobilehub-auth.com"     # Issuer c?a JWT
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
